### ISSUE TITLE
Log being flooded with messages about took longer than the scheduled update interval

### ISSUE THREAD

**Issue by fbnts** [bertbert72/HomeAssistant_VirginTivo#10]
I have this set up and working great in my HA with two Virgin Tivo boxes however I see the Home Assistant log is getting flooded with
```[homeassistant.components.media_player] Updating virgintivo media_player took longer than the scheduled update interval 0:00:01```

I don't know why, as it's all working fine.  Is there something that needs fixing or is there a way to suppress the messages.

Thanks

Tom

**Comment by bertbert72** [comment]
Not an error I've had, but it seems to be from the media_player component, which is the type that the Tivo component is based on.  I'd guess that the connection to get the latest status from the Tivo is taking longer than a second.

As to solutions, the first thing would be to make sure that nothing else is connecting to the Tivo via the network connection.  So if you have any telnet commands running separately, stop them.  The other option would be to increase the interval so it doesn't refresh as often.  Try changing `scan_interval: 1` to `scan_interval: 2` to make it refresh every 2 seconds.

**Comment by bertbert72** [comment]
Closing as no update for over 30 days.
