### ISSUE TITLE
Channel List refresh

### ISSUE THREAD

**Issue by the-jeffski** [bertbert72/HomeAssistant_VirginTivo#100]
I noticed that BBC2 three being back doesn't show on the UI as I don't think its in the channel lists. Likewise now BBC1 HD is on 101 in England this too doesn't show up.  

Looking at the sensor for BBC3 selected and I see  : 
media_title: BBC Four HD
media_series_title: This is BBC Three 13:30 - 18:58
source: BBC Four HD
prog_title: This is BBC Three
prog_description: This is BBC Three. Programmes start at 7.00pm.
prog_start_time: 2022-03-06T13:30:00
prog_end_time: 2022-03-06T18:58:00
prog_type: Movie
prog_episode_title: null
prog_episode_number: null
prog_series_number: null
base_channel_name: BBC Four HD

So not sure if this is coming back from the box or is getting converted/mapped in the code?

**Comment by bertbert72** [comment]
We had to move away from TVChannelLists as it was changed into a format that didn't give the information we need.  Any changes to TV lineups will need done to the channels.html file in the code base.  If you've noticed things that are wrong, it would be great if you could update it.

As mentioned in other places, I haven't used Home Assistant for a while which makes keeping this stuff updated a tad difficult.  However if I get a chance over the next while, I'd probably like to rewrite the channel code to use a JSON or YAML input instead, that would be a lot easier to maintain.

**Comment by bertbert72** [comment]
I've changed how this all works in v 0.26 of the component.  It uses a CSV format instead.
