### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by AngloYorkshire** [bertbert72/HomeAssistant_VirginTivo#101]
Hi,
Nice to see this and installed as said and used the example 2 for my config yaml changing the name and host to its IP Address but I can only see this in services under developer tools.
I can add a media card but it only shows what is playing on the Tivo box as an image and I can only pick a few channels to change.
I cannot watch what is playing on my Tivo on my Home Assistant.
Should I see it in the media tab as an option?
It can't be added as an integration either.

I might be looking at it wrongly
Many thanks in advance

**Comment by bertbert72** [comment]
Example 2 isn't a great one to start with.  It's specifically for people who want to defined exactly which channels to see.  The minimal example is generally a better starting point.

Adding to a media card is how this should be used.  A couple of years ago, the media card was much more suited to this, giving a full screen version of what was playing on most channels.  However it is important to note that this was never to allow you to watch your Tivo within Home Assistant.  That isn't possible and even the old version only gave a screen shot updated every minute.  The intention of the component was to allow automation tasks, things like changing channel, automatically switching to HD etc.

**Comment by AngloYorkshire** [comment]
Many thanks for the prompt reply.
This will be great if Logitech Harmony disappears alltogether.
But what is Virgin Teleport?
Thanks again

**Comment by bertbert72** [comment]
Virgin Teleport?

**Comment by AngloYorkshire** [comment]
![virgin](https://user-images.githubusercontent.com/84643957/161005062-f86faf5d-f40f-42e5-8b34-b044eb853cad.jpg)

Here you go :)

**Comment by bertbert72** [comment]
Ah ok.  That's the Tivo teleport command.  It's described in the Tivo TCP Remote Protocol documentation.  Here's the relevant section.

> **TELEPORT** 
Forces the DVR to navigate to one of several special screens: 
• TiVo Central—the top-level menu 
• Live TV—live TV viewing 
• Guide—the program guide 
• Now Playing—the list of recordings 
The TELEPORT command is guaranteed to succeed unless the DVR is in the process of Guided Setup. On success, TELEPORT does not return any response except when used with LIVETV. 
__Format__ 
TELEPORT screen 
__Parameter__ 
screen 
The screen to which the DVR should navigate, specified by one of the following strings: 
• TIVO 
• LIVETV 
• GUIDE 
• NOWPLAYING
__Example__ 
TELEPORT LIVETV 
__Responses__ 
_Success Responses_ 
LIVETV_READY TELEPORT only returns a success response when issued with LIVETV. If the command succeeds, TELEPORT returns LIVETV_READY to indicate that the DVR is now in live TV mode. Any client wishing to set a channel must wait for LIVETV_READY before issuing a SETCH or FORCECH command. 
_Failure Responses_ 
MISSING_TELEPORT_NAME Indicates that the TELEPORT command was issued without the required screen parameter
