### ISSUE TITLE
Can't pause/play 'Apps'

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#102]
For things such as YouTube, Netflix, Amazon Prime, I am no longer able to pause/play during the playback of something.
Any ideas how I can troubleshoot this?
I'm using the latest 0.1.24.

**Comment by bertbert72** [comment]
Unfortunately there's nothing that can be done about this.  During anything other than normal TV the tivo telnet interface stops responding.  It will appear to the component as if the box is on standby.  It's a limitation of the tivo TCP protocol interface.

**Comment by richard-scott** [comment]
It worked until recently?

**Comment by richard-scott** [comment]
Hmmm, it seems to have started working again in HA core-2022.4.3
