### ISSUE TITLE
TIVO Box HOST

### ISSUE THREAD

**Issue by geekwoody** [bertbert72/HomeAssistant_VirginTivo#104]
Hi,  I'm struggling to get this to work outside of entering the box's IP address. If I enter that in my YAML file it works but when I try a name it does not work:  Below is example of my YAML entry:

media_player:
  - platform: virgintivo
    force_hd: true
    tvchannellists:
      enable: true
    guide:
      enable_guide: true
    tivos:
      1:
        name: OFFICE V6 BOX
        host: TIVO-Office

My box has a name of office displayed as Office - surrounded by chevrons and in settings it says it has a TiVo Service Number:  C68-0000-2244-1C38 which looks similar to those in the examples i've seen.

within my config under host i've tried the following, but the only thing that works is if I put the IP address in, which I want to try and avoid.

host: Office (Office surrounded by chevrons)
host: Office
host: TIVO-Office
host: TIVO-<Office> (Office surrounded by chevrons)

host:  C68-0000-2244-1C38
host:  "TIVO-C68-0000-2244-1C38
host:  C68000022441C38
host:  TIVO-C68000022441C38

host: 192.168.0.30 - THIS OPTION WORKS

Any ideas as to why it's not working and at least what format I should be using?

Many Thanks,

Mark

**Comment by richard-scott** [comment]
I find that I need to use a full host name including domain. Maybe try adding .local on the host name or add a domain name if your network sets a domain name via DHCP.

**Comment by geekwoody** [comment]
> I find that I need to use a full host name including domain. Maybe try adding .local on the host name or add a domain name if your network sets a domain name via DHCP.

Thanks for the reply, I'll give that ago. Any idea which of my examples above I should use though to add the .local onto?

**Comment by richard-scott** [comment]
If your box was on my network, I'd use 'TIVO-C68000022441C38.home.lan' as its hostname as my DHCP server uses 'home.lan' as the default domain. 

I can't remember now if I added that hostname to DHCP, or if that's what the device set when it asked for an IP.

**Comment by geekwoody** [comment]
> TIVO-C68000022441C38

Hi, thanks again for the reply, I've done a bit of reading, i'm not really into and have limited understanding, but I run everything off my virgin router, and have no domain setup or configured. So don't think anything belongs to a domain.

**Comment by richard-scott** [comment]
Have a look in your VirginMedia admin console and see what name is registered there.
Then, at a command prompt, try and ping it.

if you are on a Linux box, look in '/etc/resolv.conf' to see what 'search' domain is used, that will be the domain to add.
