### ISSUE TITLE
OS 2022.12 Breaking Change?

### ISSUE THREAD

**Issue by pjrish** [bertbert72/HomeAssistant_VirginTivo#112]
After upgrading to HAOS 2022.12, my TIVO media player is "unavailable."  In the "breaking changes" documentation, there was mention that "media player groups" would be marked unavailable.  Are there any known workarounds to restore operation?

**Comment by bertbert72** [comment]
I've just updated to 2022.12 and the component is still working.  Any errors in the log?

**Comment by pjrish** [comment]
I dont see any errors related to this in the log, but it is pasted below.  Through the Dev Tools menu, I can see that none of the services were loaded for the integration.

I didn't change anything in the config.yaml or virgintivo between versions, and I've tried removing & re-installing without success to this point.

Log:
Detected blocking call to putrequest inside the event loop. This is causing stability issues. Please report issue to the custom integration author for samsungtv_custom doing blocking calls at custom_components/samsungtv_custom/samsungctl_qled/application.py, line 41: response = requests.get(APP_URL_FORMAT.format(self._ip, APPS[app]), timeout=0.2)
08:52:11 – (WARNING) util/async_.py - message first occurred at 08:35:03 and shows up 2332 times
Unexpected error fetching rinnai-202100733WZD5 data: 'maint_interval_enabled'
08:51:49 – (ERROR) Rinnai Control-R Water Heater (custom integration) - message first occurred at 08:35:19 and shows up 34 times
Error doing job: Future exception was never retrieved
08:41:02 – (ERROR) samsungtv_custom (custom integration)
Updating state for media_player.great_room_samsung_remote (<class 'custom_components.samsungtv_custom.media_player.SamsungTVDeviceQLED'>) took 0.503 seconds. Please report it to the custom integration author.
08:36:42 – (WARNING) helpers/entity.py
Cannot add light.master_shower_lights as this would exceed the 150 device limit. Consider using the filter option
08:36:33 – (WARNING) HomeKit - message first occurred at 08:36:32 and shows up 78 times
TargetHeatingCoolingState: value=0 is an invalid value.
08:36:32 – (ERROR) components/homekit/type_thermostats.py
Error setting up trigger Abnormal Humidity Notifications
08:36:31 – (ERROR) Automation - message first occurred at 08:36:31 and shows up 2 times
Error setting up trigger Abnormal Temperature Notifications
08:36:31 – (ERROR) Automation - message first occurred at 08:36:31 and shows up 2 times
Error doing job: Unclosed client session
08:36:31 – (ERROR) runner.py
Unable to connect to 192.168.1.32
08:35:25 – (ERROR) /usr/local/lib/python3.10/site-packages/roombapy/remote_client.py
Can't connect to 192.168.1.32, error: timed out
08:35:25 – (ERROR) /usr/local/lib/python3.10/site-packages/roombapy/remote_client.py - message first occurred at 08:35:17 and shows up 3 times
Config entry 'Downstairs Thermostat' for homekit_controller integration not ready yet: Timeout while waiting for connection to device 192.168.1.20:80; Retrying in background
08:35:22 – (WARNING) config_entries.py - message first occurred at 08:35:15 and shows up 6 times
Setup of media_player platform dlna_dmr is taking over 10 seconds.
08:35:16 – (WARNING) Media player - message first occurred at 08:35:14 and shows up 5 times
Setup of automation is taking over 10 seconds.
08:35:14 – (WARNING) runner.py
API is back online.
08:35:06 – (WARNING) Govee (custom integration)

My config.yaml follows version 2:

`#####################################
#TIVO Remote
media_player: 
  - platform: virgintivo
    tivos:
      1:
        name: Great Room TIVO
        host: 192.168.1.13
      2:
        name: Bonus TIVO
        host: 192.168.1.12
    tvchannellists:
      enable: false
    channels:
      1002:
        name: ABC
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/2/2f/ABC-2021-LOGO.svg/revision/latest?cb=20220228011330

....and so forth

**Comment by pjrish** [comment]
After further troubleshooting, this doesn't appear to be a virgintivo / OS 2022.12 problem.  I disabled several non-essential items in my configuration.yaml and reverted to virgintivo v.25 and it is working again.  There is something specific in my configuration that HA doesn't like, so I will troubleshoot further.  

Thank you for your help and for this integration!
