### ISSUE TITLE
Query on guide...

### ISSUE THREAD

**Issue by ptruman** [bertbert72/HomeAssistant_VirginTivo#114]
Good integration!
Is the guide supposed to be visible? (just wondering - as I can't see how to access it if it's supposed to be accessible)
(also, for teleport, are things like LIVETV supposed to be passed as a parameter via YAML?)

**Comment by bertbert72** [comment]
The guide feeds into whichever media player component you are using to display the current programme.  

![image](https://github.com/bertbert72/HomeAssistant_VirginTivo/assets/7685189/0b42c7f8-dcfd-4aa0-ab93-6f2e8703b960)

For the teleport command you use YAML to set the data parameter appropriately, e.g.

![image](https://github.com/bertbert72/HomeAssistant_VirginTivo/assets/7685189/ed235c29-25ba-46a9-bb22-f387c0315c7b)

**Comment by ptruman** [comment]
Thanks - I was wondering if it was exposed/exposable as a sensor? (kind of like this attempt).
Prob a moot point soon as VM have killed the V6 off - I'm not looking forward to when mine dies :\

**Comment by bertbert72** [comment]
Whilst it would be perfectly possible to do something like this, it probably isn't going to get done, at least by me.  My V6 box has already been replaced and I imagine everyone else's will be over the next few months. 

However the entity has a number of states which give most of the details you are after:

![image](https://github.com/bertbert72/HomeAssistant_VirginTivo/assets/7685189/4c341cb4-7b56-47f9-bec1-5d45cdc92864)
