### ISSUE TITLE
Ref Issue 109: 4-digit Channel IDs

### ISSUE THREAD

**Issue by pjrish** [bertbert72/HomeAssistant_VirginTivo#119]
Good morning,

For thos of us in the USA, many providers use 4-digit channel codes.  Changing line 108 to the following fixes the configuration and compatibility issues:

`CHANNEL_IDS = vol.All(vol.Coerce(int), vol.Range(min=1, max=9999))`

Thank you!

**Comment by almoney** [comment]
This is old, but I started looking at Home Assistant TiVo integration.  @pjrish, are you using Virgin Tivo in the US?

**Comment by pjrish** [comment]
> This is old, but I started looking at Home Assistant TiVo integration. @pjrish, are you using Virgin Tivo in the US?

Yes, Comcast / XFinity.

**Comment by almoney** [comment]
@pjrish Nice. Would you mind sharing your configuration?

**Comment by pjrish** [comment]
@almoney here is what I have been using.  Also remember I had to change a line in the source code, as mentioned above.  This has been working for about 2 years +/-.  Hope this helps!

`media_player: 
#TIVO#
  - platform: virgintivo
    tivos:
      1:
        name: Great Room TIVO
        host: 192.168.1.13
      2:
        name: Bonus TIVO
        host: 192.168.1.12
    tvchannellists:
      enable: false
    channels:
      1002:
        name: ABC
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/2/2f/ABC-2021-LOGO.svg/revision/latest?cb=20220228011330
      1004:
        name: NBC
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/d/d5/NBC_2014_Indent_Style.svg/revision/latest?cb=20200906124625
      1005:
        name: CBS
        show: true
        logo: https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/cbs-logo-white-us.png
      1008:
        name: PBS
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/c/c8/PBS_2019.svg/revision/latest/scale-to-width-down/1000?cb=20220214092153
      1017:
        name: FOX
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/e/e3/Fox_2019.svg/revision/latest?cb=20220925085535
      1102:
        name: Weather Channel
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/a/a6/The_Weather_Channel_%282005%29.svg/revision/latest/scale-to-width-down/48?cb=20171128103430
      1110:
        name: Fox News
        show: true
        logo: https://logos.fandom.com/wiki/Fox_News_Channel#2017%E2%80%93present
      1111:
        name: CNN
        show: true
        logo: https://logos.fandom.com/wiki/CNN#2014%E2%80%93present
      1205:
        name: ESPN
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/3/34/ESPN.svg/revision/latest/scale-to-width-down/300?cb=20201130040927
      1206:
        name: ESPN2
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/e/ee/ESPN_2_logo_2003.svg/revision/latest/scale-to-width-down/200?cb=20091117174135
      1321:
        name: SEC Network (Main)
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/9/9e/SEC-network-horizontal.svg/revision/latest/scale-to-width-down/250?cb=20161125152750
      1322:
        name: SEC Network (2)
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/9/9e/SEC-network-horizontal.svg/revision/latest/scale-to-width-down/250?cb=20161125152750
      1323:
        name: SEC Network (3)
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/9/9e/SEC-network-horizontal.svg/revision/latest/scale-to-width-down/250?cb=20161125152750
      1403:
        name: USA
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/7/70/USA_Network_2005.svg/revision/latest/scale-to-width-down/78?cb=20171123125933
      1404:
        name: TNT
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/f/f4/TNT_2016.svg/revision/latest/scale-to-width-down/48?cb=20201128113457
      1405:
        name: AMC
        show: true
        logo: https://logos.fandom.com/wiki/AMC_(TV_network)#2019%E2%80%93present
      1409:
        name: FX
        show: true
        logo: https://logos.fandom.com/wiki/FX_(United_States)#2022%E2%80%93present
      1410:
        name: FXX
        show: true
        logo: https://logos.fandom.com/wiki/FXX#2013%E2%80%93present
      1411:
        name: SYFY
        show: true
        logo: https://logos.fandom.com/wiki/Syfy#2017%E2%80%93present
      1434:
        name: TBS
        show: true
        logo: https://logos.fandom.com/wiki/TBS_(United_States)#2015%E2%80%93present
      1435:
        name: Comedy
        show: true
        logo: https://logos.fandom.com/wiki/Comedy_Central#2018%E2%80%93present
      1449:
        name: Discovery
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/2/2a/DSC_DGlobe_2016_Reverse.svg/revision/latest/scale-to-width-down/48?cb=20170504003819
      1450:
        name: TLC
        show: true
        logo: https://logos.fandom.com/wiki/TLC_(TV_network)#2006%E2%80%93present
      1473:
        name: National Geographic
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/c/c6/National_Geographic_2008.svg/revision/latest/scale-to-width-down/300?cb=20170701154034
      1478:
        name: History
        show: true
        logo: https://logos.fandom.com/wiki/History_(United_States)#2021%E2%80%93present
      1484:
        name: Food Network
        show: true
        logo: https://logos.fandom.com/wiki/Food_Network_(United_States)#2013%E2%80%93present
      1488:
        name: Travel
        show: true
        logo: https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/travel-channel-us.png
      1492:
        name: HGTV
        show: true
        logo: https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/hgtv-us.png
      1715:
        name: Disney
        show: true
        logo: https://static.wikia.nocookie.net/logopedia/images/f/ff/Disney_channel_2019.svg/revision/latest/scale-to-width-down/78?cb=20220920223409
`

**Comment by almoney** [comment]
I have too many TiVos so I also increased the number of TIVO_IDS to 50 on line 105:

TIVO_IDS = vol.All(vol.Coerce(int), vol.Range(min=1, max=50))
