### ISSUE TITLE
HASS update has broken it :\

### ISSUE THREAD

**Issue by ptruman** [bertbert72/HomeAssistant_VirginTivo#121]
Top integration and I've been using it for ages - but a recent update to HASS appears to have nobbled it

Currently getting this:

`Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:361
integration: Media Player ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 21:38:20 (1 occurrences)
Last logged: 21:38:20

Error while setting up virgintivo platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/virgintivo/media_player.py", line 230, in setup_platform
    hass.data[DATA_VIRGINTIVO].append(VirginTivo(extra[CONF_HOST], channels, tivo_id, extra[CONF_NAME],
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/virgintivo/media_player.py", line 330, in __init__
    self.get_guide_channels()
  File "/config/custom_components/virgintivo/media_player.py", line 341, in get_guide_channels
    for channel in channels_data["channels"]:
                   ~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
`

Haven't changed anything in TiVo hass config, just updated HASS docker.
Reloading hass doesn't cure it - but randomly I edited media_player.tivo and deliberately introduced an error on line 361, restarted hass, removed the error, restarted it and it reloaded ok.
Probably me - so apologies if that's the case :)

**Comment by bertbert72** [comment]
Just tried updating to the latest HASS and hasn't broken as far as I can see.  That bit of the code grabs the channels from Horizon.  Maybe it glitched and something unreadable came back.
