### ISSUE TITLE
Update request for newer HASS releases

### ISSUE THREAD

**Issue by ptruman** [bertbert72/HomeAssistant_VirginTivo#122]
Hi

Getting this in the logs (yup, still rocking a TiVo and this v nice integration) :)

_MEDIA_TYPE_TVSHOW was used from virgintivo, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.TVSHOW instead, please report it to the author of the 'virgintivo' custom integration_

**Comment by almoney** [comment]
I created a pull request to maintain HA compatibility.
