### ISSUE TITLE
Problem with the latest release.

### ISSUE THREAD

**Issue by MikeHCam** [bertbert72/HomeAssistant_VirginTivo#129]
Hi

I just installed the latest release and now get the following error:

Logger: py.warnings
Source: util/loop.py:200
First occurred: 7:46:47 AM (1 occurrences)
Last logged: 7:46:47 AM

/config/custom_components/virgintivo/media_player.py:1254: SyntaxWarning: invalid escape sequence '\d' channel_no = re.match('\d+', str_channel_id)[0]

I am a programmer of many years standing but I have always managed to avoid having to use Python. But I am in the process of migrating from Habitat to Home Assistant and so am now on a forced learning curve. This is obviously a regular expression syntax error, which I will try to work out myself. And if I do so, I will post a fix. But I imagine someone who knows Python might be able to correct it much quicker.

Thanks

Mike

**Comment by bertbert72** [comment]
Just a change in the Python versions, surprised it isn't happening for everyone.  But should be ok in new version.

**Comment by MikeHCam** [comment]
Many thanks for fixing this. Didn't expect a response quite so quick, but I thought you would be able to fix it a lot quicker than me. Particularly as I am also helping cook for tomorrow. Happy Holidays!
