### ISSUE TITLE
Anyway to detect playing behind live? 

### ISSUE THREAD

**Issue by FattusMannus** [bertbert72/HomeAssistant_VirginTivo#17]
So often I play TV behind the live picture. 

Therefore, the picture in HA doesn’t match anywhere what’s on the TV. 
I see that the picture in HA comes from virgin go. 

Is there any way to: 
* detect that I’m behind live
* use that offset with virgin go to get a more accurate thumbnail? 

Thanks
Andrew

**Comment by bertbert72** [comment]
Afraid not on both questions.  The Tivo Remote Network protocol is very basic and doesn't have this functionality available.
