### ISSUE TITLE
Loading Netflix or YouTube Apps shows Virgin box as Off

### ISSUE THREAD

**Issue by FattusMannus** [bertbert72/HomeAssistant_VirginTivo#18]
Choosing Home > Search and Discover > Netflix/YouTube causes the Virgin box to show as Off. 

I assume this is because it isn’t broadcasting a channel. Is there anyway to improve this to at least show the box is on, even if the specific app isn’t displayed? 

Thanks
Andrew

**Comment by bertbert72** [comment]
Again, no there isn't.  When the box is "off", it responds exactly the same as when it is playing something.  This is a known limitation of the Tivo.  Unless they decide to expose a more advanced API, there's not much that can be done.
