### ISSUE TITLE
Integration virgintivo not found in 0.92

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#26]
I have just updated Home Assistant to 0.92 and I now get this error:

```
Integration virgintivo not found when trying to verify its media_player platform
```

It was working before the upgrade  ;-(

**Comment by richard-scott** [comment]
Ah, it seems they broke it in the latest update of Home Assistant:

See this issue: https://github.com/home-assistant/home-assistant/pull/22878

**Comment by bertbert72** [comment]
Sounds awesome.  I'll upgrade tonight and see what is going on.  I assume you already changed the component to be custom_components/virgintivo/media_player.py?

**Comment by garywilson4** [comment]
Hope you can fix it

**Comment by bertbert72** [comment]
As of 0.92 all components need a manifest file. Stick this into the custom_components/virgintivo folder:

https://raw.githubusercontent.com/bertbert72/HomeAssistant_VirginTivo/master/custom_components/virgintivo/manifest.json

**Comment by richard-scott** [comment]
Adding that file helps. Thanks for the work on this project.

I've updated the installation notes of the README.md in this https://github.com/bertbert72/HomeAssistant_VirginTivo/pull/29
