### ISSUE TITLE
Channel 5 HD showing up as "["

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#38]
They have changed the format of the fields on [here](https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK)).

The entry for "Channel 5 HD" currently looks like this:
<br><br>

![image](https://user-images.githubusercontent.com/5149834/72156375-4ba9cf00-33ad-11ea-9cf6-2fa300dce1c8.png)

And "Channel 5" looks like this:
<br><br>
![image](https://user-images.githubusercontent.com/5149834/72156415-62502600-33ad-11ea-8351-feccb97488b7.png)

In Home Assistant it show up like this:
<br><br>
![image](https://user-images.githubusercontent.com/5149834/72156559-c1159f80-33ad-11ea-98e3-a045363ee90d.png)

and this:
<br><br>
![image](https://user-images.githubusercontent.com/5149834/72156586-d68ac980-33ad-11ea-8798-b4ae1fd79ac9.png)

**Comment by bertbert72** [comment]
Thanks for letting me know.  I've fixed the TVChannelLists page.

**Comment by richard-scott** [comment]
Thanks... I've signed up for an account, I was going to do the same if I could not figure out a way to do it in code 😂
