### ISSUE TITLE
Channel Guide is one hour out 

### ISSUE THREAD

**Issue by ashdwells** [bertbert72/HomeAssistant_VirginTivo#39]
Hi 

I am having an issue with the program being displayed. I am currently watching channel 4 after 9pm but it display the program that was on 8-9 and claims its on 9-10

Help please

**Comment by richard-scott** [comment]
What timezone is your HA Server using?
Look in "Developer Tools" -> "Info" -> "System Health" -> "timezone"

**Comment by ashdwells** [comment]
Says GB

**Comment by ashdwells** [comment]
Only seems to happen with Channel 4 that i have noticed

**Comment by bertbert72** [comment]
Sounds like it thinks you are on Channel 4+1 for some reason.  ln the HomeAssistant UI, go to Developer Tools > States and filter for your box, e.g. Virgin and see what the attributes are.  E.g.

```
media_content_type: tvshow
media_duration: 1800
media_position: 509
media_title: E4 HD
media_series_title: The Big Bang Theory S 7, Ep 6: The Romance Resonance 20:30 - 21:00
source: E4 HD
source_list: BBC One HD,BBC Two HD,ITV,Channel 4,Channel 5 HD,E4,Sky One,ITV2,ITV3,ITV4,Universal TV HD,Gold HD,Alibi,Dave,Comedy Central HD,Sky Crime HD,E! HD,More4,Film4,RTÉ One,RTÉ 2
prog_title: The Big Bang Theory
prog_description: Sheldon's latest scientific breakthrough leaves him feeling like a fraud.
prog_start_time: 2020-02-05T20:30:00
prog_end_time: 2020-02-05T21:00:00
prog_type: TV
prog_episode_title: The Romance Resonance
prog_episode_number: 6
prog_series_number: 7
base_channel_name: E4
friendly_name: Virgin V6
entity_picture: /api/media_player_proxy/media_player.virgin_v6?token=690b2d8287853bbf0d192930782074bdb263e8495e7f67b9bff7d5b19a1f1c51&cache=70faca363fba78bf
supported_features: 22961
```

**Comment by ashdwells** [comment]
Hi here’s what it says and again is an hour behind 
![7FB674B4-236A-4BF7-A054-DF35BE13E50C](https://user-images.githubusercontent.com/22473771/74190719-b53a2900-4c4a-11ea-9ca0-2f6148c5f8a1.jpeg)

**Comment by bertbert72** [comment]
Could you show me your configuration,.yaml just the bit for the component?  Also on your Tivo, what are the channel numbers for Channel 4, Channel 4 HD and Channel 4+1?

**Comment by ashdwells** [comment]
- platform: virgintivo
    tivos:
      1:
        name: Virgin TV
        host: 192.168.0.**
        force_hd: true 
    tvchannellists:
      enable: True
      override:
        101:
          name: BBC One
          package: Player
          is_hd: False
        108:
          name: BBC One HD
          package: Player
          is_hd: True
        104:
          name: Channel 4
          package: Player
          is_hd: False
        105:
          name: Channel 5
          package: Player
          is_hd: False
        141:
          name: Channel 4 HD
          package: Player
          is_hd: True
    guide:
      enable_guide: true
      picture_refresh: 60
      cache_hours: 12

Channel 4 is 104
channel 4 HD is 141 
channel 4 +1 is 142

**Comment by bertbert72** [comment]
Ok, I think we'll need debug logging to try to work out what is going on.  It looks like it must be somehow tagging Channel 4 HD as a +1 channel..  We can tell this for certain with the logging since it logs which channels it does the +1 offset for when creating the guide.  We'll then just need to work out why...

To enable logging you need to change your configuration a bit:

```
logger:
  default: error
  logs:
    custom_components.media_player.virgintivo: debug

```

Then send me the log.  One final question.  Is it consistently an hour out, or just occasionally?

**Comment by bertbert72** [comment]
If this is still an issue, please let me know otherwise I'll close it.
