### ISSUE TITLE
Unable to fetch channels

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#47]
I'm getting this error today:

```
Log Details (ERROR)
Logger: custom_components.virgintivo.media_player
Source: custom_components/virgintivo/media_player.py:182
First occurred: 9:30:04 AM (1 occurrences)
Last logged: 9:30:04 AM

Could not fetch channel listings from https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK), error list index out of range
```

I wonder if the adverts are causing html parsing issues?

![2020-04-21 11_26_45-Window](https://user-images.githubusercontent.com/5149834/79855631-24f32f80-83c3-11ea-9703-6aaa8c748dd0.png)

**Comment by bertbert72** [comment]
Going to close this one and we'll track under #48.  It's the same thing.
