### ISSUE TITLE
virgintivo: Error on device update - KeyError: 702

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#48]
Unable to use the add-on at all today ;-(

```
Log Details (ERROR)
Logger: homeassistant.components.media_player
Source: custom_components/virgintivo/media_player.py:498
Integration: Media player (documentation, issues)
First occurred: 9:30:04 AM (1 occurrences)
Last logged: 9:30:04 AM

virgintivo: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 324, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/virgintivo/media_player.py", line 576, in update
    override_idx = self.override_channel(new_channel_id)
  File "/config/custom_components/virgintivo/media_player.py", line 498, in override_channel
    if self._force_hd_on_tv and self._channels[channel_id][CONF_HDCHANNEL] and not self._sdoverride['enabled']:
KeyError: 702
```

**Comment by mastermc0** [comment]
From a quick check it looks like this is due to the site being used to pull the channel list being updated to have tables in a new format.  I’m gonna have a play around later and see if I can confirm this.

Will let you know how I get on.

**Comment by bertbert72** [comment]
Yes, looks like the table structure was changed yesterday.  I've only had a very quick look.  I'll have a more thorough check tonight to see.  That's the problem with web scraping - you're always at the mercy of changes to the site

**Comment by mastermc0** [comment]
> have

Was gonna have a crack myself but given I bumble my way through Python I’ll leave it to you.

**Comment by bertbert72** [comment]
Feel free to have a go if you like.  It's not like that section of the code is going to win any beauty prizes.  The bit that parses the site is under get_channel_listings.  It combines any override definitions within the configuration with whatever it gleans from the site.  Hacks abound!  The whole bit could do with a proper tidy,

Otherwise I'll have a go tonight.  Can't actually access the site from my work laptop to see the details of what has changed.  Just what I can view on my phone.  I can see that there are now separate columns for HD and SD, but don't know what else was done.

**Comment by bertbert72** [comment]
Hopefully that is now working in the latest release.  Limited testing as kids are watching the TV and don't appreciate me mucking about too much.  Let me know if any issues.

**Comment by mastermc0** [comment]
All good here nice one on the quick fix!

**Comment by richard-scott** [comment]
Thanks for the fix :-)
