### ISSUE TITLE
Something is broken in HA 0.109

### ISSUE THREAD

**Issue by volpmatt** [bertbert72/HomeAssistant_VirginTivo#51]
Entity has disappeared from config.

**Comment by bertbert72** [comment]
I've updated to 0.109.1 and everything still works.  Can you provide more detail about what you're experiencing, e.g. logs?

**Comment by richard-scott** [comment]
I have had that happen when my VirginMedia box is either off or has no network connectivity when restarting HA... mayby confirm that the Virgin Box has valid IP settings and try restarting HA.

I have found recently that over night my HA box doesn't seem to want to renew its DHCP IP, so maybe that's not just a problem on my setup.

p.s. I'm on 0.109.1 and its fine for me too.

**Comment by volpmatt** [comment]
I've just reinstalled the component from scratch and it's working again. Idk what happened but thought it was worth mentioning! Cheers.

**Comment by eyelock** [comment]
I encountered a similar behaviour when restarting my HA 0.109.6 last night and the previous virgintivo entity disappearing.  It took a few restarts to understand it with enable debug to understand the general gist of the problem. 

I was watching CH4 HD on the box when restarting HA, which in my region is on channel 141.  At start in the debug log I can see that the JSON downloaded has CH4 HD on channel 4.  At one point there is a `KeyError: 141` and the component never starts up and appears as a HA entity.

I fixed it by changing to a well known channel (BBC One HD) and restarting HA, the component came back.

Apologies can't offer a fix, but could help someone else who is scratching their head into the wee sma' hours.

**Comment by bertbert72** [comment]
If you can give me the full stack trace for the error from the log, I can patch it up.

**Comment by eyelock** [comment]
@bertbert72 I fixed it this morning using https://github.com/bertbert72/HomeAssistant_VirginTivo/issues/53#issuecomment-626210112, I'll break it again tonight and get a stack track (sorry, should have grabbed at time).

**Comment by bertbert72** [comment]
See if that works a bit better now.  It'll stick a warning in the logs if the channel isn't in the configuration
