### ISSUE TITLE
How do I add this to home assistant?

### ISSUE THREAD

**Issue by JasonD95** [bertbert72/HomeAssistant_VirginTivo#6]
Having trouble getting this to work. Could you provide further instruction for a bit of a newb?

**Comment by JasonD95** [comment]
I've managed to get everything to appear in the hassio web interface, though none of the automations/switches for the channels actually work. I'm not really sure what I'm doing wrong?

**Comment by bertbert72** [comment]
Hi Jason,

If you mean the Alexa automations, questions are probably best posted in the community forum for this at

https://community.home-assistant.io/t/control-tivo-box-over-telnet/12430

The Alexa automations were done by a couple of the guys on there.  I'm afraid I don't have an Alexa so I'd be guessing a bit :)

Anything else, I'll be able to help you with.  But again, best posting in the forum as more people will be able to respond.

If your problem isn't just the automations but also the change channel / channel info stuff isn't working either, I'd suspect either your config for the box is wrong (post up any errors related to the Virgin Tivo component) or that you haven't enabled Network Control in your Tivo settings.

**Comment by JasonD95** [comment]
Hi,

I can't get the alexa automation working but that's secondary at the moment. What I meant was the automations that show up on the overview panel of hassio. They all show up on the screen, but nothing happens when I click to trigger them. I've probably missed something obvious. 

I can change channels to a select few (I think I figured out what decided which channels were shown last night but I was tired) through the card for the virgin box I've set up on hassio, and turn it on and off, but that's about it. I'm trying to figure this out as I go along but I don't seem to be getting much support from the 'official' channels, or they all act as if I'm supposed to know the system inside out before I do ask.

Will post anything you may need to see this evening if there is anything that will help. 

Thanks

**Comment by JasonD95** [comment]
Yeah I'm not getting anywhere fast with this. I'll give that thread a try then if that's the best place to go, thank you. 

Perhaps there is one thing you may be able to tell me though - in the Virgin TiVo component, I only get a certain few channels that I can change to in the "source" box (will post a screenshot if I'm not making myself clear). How do I set/change what they are?

**Comment by bertbert72** [comment]
Regarding the channels that appear in the dropdown, that is controlled by the _show_ attribute.  For example:

```yaml
      106:
        name: E4
        show: true
        package: Player
        hd_channel: 145
        plus_one: 146
      107:
        name: BBC Four
        package: Free-to-air
        hd_channel: 163
```

Channel 106 will appear because _show_ is true, but 107 won't.

**Comment by JasonD95** [comment]
Yeah I realised I'd missed that on the main page so I was being a bit thick there, thank you anyway though (tried to edit that before I made myself look an idiot but I guess the email notifications did for me!).
