### ISSUE TITLE
invalid literal for int()

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#62]
I still get channles listed in the UI, but there is this error in the logs.

```
Log Details (ERROR)
Logger: custom_components.virgintivo.media_player
Source: custom_components/virgintivo/media_player.py:186
Integration: virgintivo (documentation)
First occurred: 11:02:33 (1 occurrences)
Last logged: 11:02:33

Could not fetch channel listings from https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK), error invalid literal for int() with base 10: 'On-Demand'
```

**Comment by bertbert72** [comment]
They are still hacking away at the site with 9 changes since I made the fix last night.  I've just restarted my instance and now I get the same error.  I'll have a look tonight to see what is going on.

**Comment by bertbert72** [comment]
Until I get it sorted, you can point to a version of the guide that works from yesterday:

```
    tvchannellists:
      enable: True
      url: https://www.tvchannellists.com/index.php?title=List_of_channels_on_Virgin_Media_(UK)&oldid=71327
```

**Comment by bertbert72** [comment]
That should be a slightly more robust fix, but they changed one of the table structures.  There's not much I can do except fix the code when it happens.
