### ISSUE TITLE
No 'version' key in the manifest file 

### ISSUE THREAD

**Issue by ysbs** [bertbert72/HomeAssistant_VirginTivo#74]
Latest version of HomeAssistant gives the error:
WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'virgintivo'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'virgintivo'

**Comment by MightyWomble2020** [comment]
Same for me too.

**Comment by bertbert72** [comment]
Thanks @richard-scott for the PR

Unfortunately my Esxi server bit the dust a few weeks ago so I don't have a working system.  With work commitments I've not had the chance to rebuild it.  Some day though...
