### ISSUE TITLE
Channel List Error

### ISSUE THREAD

**Issue by ColinRobbins** [bertbert72/HomeAssistant_VirginTivo#82]
Hello, I am seeing the error:
```
Unable to load channels from [https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK)] code [200], trying cache
```
I think the URL may have changed, as the list of channels is now
```https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK)_-_New_Packages```
or
```https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK)_-_Old_Packages```
depending upon your package.

I resolved it by adding 
```
  tvchannellists:
    url: https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK)_-_Old_Packages
```
to my config.

Not sure what the full solution is, maybe a documentation update?

**Comment by bertbert72** [comment]
There was a fix done for this last week to point to the new packages - #80.  Make sure you are using the latest code.  If you want to use the old package list, then use the url as you described.  Let me know if that doesn't work for you.

**Comment by ColinRobbins** [comment]
Thanks, all working now.
Note quite sure what happened, I did update via HACS, but still saw the issue.
However, I’ve now removed the `url` config line, restarted HA and it’s all working fine.
Cheers,
