### ISSUE TITLE
Getting status of box

### ISSUE THREAD

**Issue by MichaelNMaggs** [bertbert72/HomeAssistant_VirginTivo#85]
Apologies if this is a very basic question, but is there a way of getting the Tivo status, ie on / standby / off?  I'd like to make use of on / standby as a binary sensor, but have no idea what to put in the yaml.

**Comment by bertbert72** [comment]
Only 2 years too late (sorry!), but the answer is "not reliably".  The box effectively stops responding when it is on standby, but it also stops responding when doing anything other than watching live tv, e.g. watching a recording.  Sadly we've a very limited interface to work with.
