### ISSUE TITLE
TV Channels List blocking bots

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#92]
I’ve noticed that the tv listing site now has a captcha check blocking web scraping 😧

https://www.tvchannellists.com/w/List_of_channels_on_Virgin_Media_(UK)_-_New_Packages

**Comment by richard-scott** [comment]
Ok, a work around is to go to the page in “private browsing” mode, manually pass the captcha and use the provided url in the tvchannellists section of your config.

The Url you get is something like this:

https://www.tvchannellists.com/w/List_of_channels_on_Virgin_Media_(UK)_-_New_Packages?__cf_chl_managed_tk__=pmd_AUc8Q9Edq0sUCjyzKRsRusHQcw7.-1631224677-0-gqNtZGzNAvujcnBszRH9

**Comment by bertbert72** [comment]
The format of the site is no longer compatible with the component.  I've created a cut of the relevant tables from the last working copy I have and put it into GitHub.  We'll have to use it from now on.
