### ISSUE TITLE
implements device_state_attributes warning

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#96]
I've noticed this in my HA Logs:
![Screenshot 2022-02-03 at 15 09 56](https://user-images.githubusercontent.com/5149834/152370068-9353bb8a-e858-4fad-bede-6ca2b45d6f8d.png)

**Comment by PhilDGeorge1968** [comment]
Hi, thanks for looking at this. 
I also had this warning in my log file but your change from 3 days ago looks to have worked - the component still appears to be working and the warning has gone
