### ISSUE TITLE
Selecting Channel 103 ITV HD does not work.

### ISSUE THREAD

**Issue by Caleroific** [bertbert72/HomeAssistant_VirginTivo#97]
I have set this up and am very pleased with it but one thing. The drop down menu shows ITVHD and I can select it but the TIVO box does not switch to 103 ITV HD. If I use the TIVO remote I can select 103 ITV HD and the change is reflected in the app. It looks like the spp allows me to select the correct channel but for some reson or other it is not communicating correctly with the TIVO box.

All other channels are OK. I can select ITV SD 113 OK.

Could this be something to do with Channel 103 bwing switched form SD to HD?

Thank you

**Comment by bertbert72** [comment]
Probably need to stick on debugging to see what it is doing.  Add the following to your configuration and then send me the logs.

```
logger:
  default: error
  logs:
    custom_components.media_player.virgintivo: debug
```

Also can you give me your config?  If you've got an override in there that isn't valid, that could cause it.
