### ISSUE TITLE
Incorrect Channel Configuration for Channel 141 (Channel 4 HD)

### ISSUE THREAD

**Issue by 91JJ** [bertbert72/HomeAssistant_VirginTivo#99]
As description, and screenshot below...
The integration still works, just getting the error.

![image](https://user-images.githubusercontent.com/49962077/156887917-f7b0fec4-9eac-46be-8ec0-9182898bad8e.png)

**Comment by bertbert72** [comment]
This error means that channel 141 doesn't exist in your list of channels.  Make sure you either have tvchannellists mentioned in your conf file or that you have 141 explicitly in your list of channels if you are doing it that way.  Post up your conf if you want me to have a look at it.
